# AgentInstanceType = "c5n.xlarge"
# ApiMaxRetries = 1
# AppInstanceType = "c5.xlarge"
# InboundIPv4CidrBlocks = [ "0.0.0.0/0" ]
# PrivateSubnetAvailabilityZone = "us-east-1a"
# PublicSubnetAvailabilityZone = "us-east-1a"
# Region = "us-east-1"
# UserEmailTag = "terraform@example.com"
# UserLoginTag = "terraform"
# UserProjectTag = "cloud-ist"