# Private1SubnetName = "terraform-example-test-01-subnet"
# Private1VpcNetworkName = "terraform-example-test-01-vpc-network"
# Private2SubnetName = "terraform-example-test-02-subnet"
# Private2VpcNetworkName = "terraform-example-test-02-vpc-network"
# ProjectId = "example"
# PublicSubnetName = "terraform-example-management-subnet"
# PublicVpcNetworkName = "terraform-example-management-vpc-network"